[workspace]
resolver = "3"
members = [
  'apps/desktop',
  'apps/headless',
  'crates/editor-core',
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
fs2 = "0.4.3"
gpui = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.9"
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0"
ttf-parser = "0.25.1"
uuid = { version = "1.18", features = ["v4", "serde"] }
